### PR TITLE
add some keys...

### PR DESCRIPTION
**Pull request by r-type**
@twinaphex  i bet you can add me the admin of this repository as the upstream is my own !

### CODE REVIEW

**Comment by r-type** [comment]
@twinaphex any reason you don't merge the PR ?

**Comment by xTMODx** [comment]
will the core then be available for android? if yes cant wait for the merge too :)

**Comment by r-type** [comment]
it works fine in android http://dl.free.fr/emdutAQzd1

**Comment by xTMODx** [comment]
So only the buildbot is not prepared yet?

**Comment by r-type** [comment]
It miss this PR , and then Buildbot recipe for win/lin/android.

**Pull request merged**
