### PR TITLE
Revert da7893488b18f18282f2f3a121bb4c13df947a99

### PR DESCRIPTION
**Pull request by cmitu**
Looks like I made an error and the fix is incomplete - causing a build failure. Please revert until I find a better version. Sorry for the mishap.

### CODE REVIEW

**Comment by masaklaw** [comment]
> Looks like I made an error and the fix is incomplete - causing a build failure. Please revert until I find a better version. Sorry for the mishap.

@cmitu @twinaphex - to make this fix good, just replace `volume.s16` with `65535.0` and `volume.s8` with `255.0`.

**Comment by twinaphex** [comment]
Can you send a PR for this please?

**Comment by cmitu** [comment]
@masaklaw - does https://github.com/cmitu/libretro-atari800/tree/sound-fix-bis work fine for you ?

**Comment by masaklaw** [comment]
It does not compile:
```
libretro/libretro-core.c: In function ‘retro_get_system_info’:
libretro/libretro-core.c:575:36: error: expected ‘;’ before ‘GIT_VERSION’
  575 |    info->library_version  = "3.1.0" GIT_VERSION;
      |                                    ^~~~~~~~~~~~
      |                                   
```

**Pull request merged**
