### PR TITLE
enable individual configuration files for lr-atari800

### PR DESCRIPTION
**Pull request by Neo-Stone**
- introduce new core option: atari800_individualconfiguration
- if set to "enabled" the lr-atari800 emulator will work with configuration files that rely on the calling emulator name. The configuration filenname has to have exactly the name of the corresponding emulator plus a .cfg ending.
- more (and detailed) information to be found here:  [Individual configurations for the lr-atari800 emulator](https://github.com/Neo-Stone/lr-atari800-individualconfiguration-helper)

### CODE REVIEW

**Comment by raphkoster** [comment]
Interesting, and thanks so much for carefully reading all that stuff I wrote!

The thing I wonder about is whether this should instead all just go in the Core Options menu but just update the cfg, rather than requiring a bunch of parallel emulator executables.

**Comment by Neo-Stone** [comment]
Hi raphkoster,

thanks for your comment. 
> The thing I wonder about is whether this should instead all just go in the Core Options menu but just update the cfg, rather than requiring a bunch of parallel emulator executables

This might be another possible solution I think. Actually I am not sure which one might be better. 
I can see the following points:

- Putting all functionality into the core options menu would add a lot of functionality to it which exists already in the configuration file. Also the size of the core options menu will increase a lot.
- In addition you will have to save one `OPT` file for every rom, you want to configure different from the standard. So you might get a lot of `OPT` files.

In my actual solution you don't need any `OPT` files at all and can use one configured emulator for several roms, so reusability is given. I do also think that just selecting a different emulator for a rom is an easy and transparent way in retroarch for a user. 

So maybe you will give it a try and test it? I would be really glad to get some feedback.

**Comment by Darknior** [comment]
I love this idea :)
Really wish to have this option for Atari 800 :)

**Comment by raphkoster** [comment]
I'll give it a try at some point -- my day job is keeping me very busy right now!

How would this work on platforms that aren't the RPI? This repo gets compiled for all retroarch platforms.

> In my actual solution you don't need any OPT files at all and can use one configured emulator for several roms, so reusability is given. I do also think that just selecting a different emulator for a rom is an easy and transparent way in retroarch for a user.

It won't create .OPT files, but it will still create a file per game, iirc, that overrides the default emulators.cfg, when you choose a different core from the runcommand menu.

My thought was to simply extend the core option that lets you select which machine, and add more choices to it. So still preset configurations, but just more of them. The advantage here is that it then works like all the other cores do.

I definitely don't think that we should replicate the full extent of the emulator's options in the Core Options menu, they get very fiddly. But just adding the artifacting option would already open up quite a lot of these.

If the user is using a properly tagged romset, things like [OSb] and the like should already be present in the filename, whereupon we could make the emulator switch to the right config automatically. (My runcommand script did this).

**Comment by Neo-Stone** [comment]
> How would this work on platforms that aren't the RPI? This repo gets compiled for all retroarch platforms.

My implementation is totally `RPI` **independent**! So it should work without any problems on all libretro platforms. Of course some testing should be done there.

Personally I do only have to possibility to test on my `RPI` (which I have done a lot!). For this reason my  [(helperfiles)](https://github.com/Neo-Stone/lr-atari800-individualconfiguration-helper) are - of course -  all written for the `RPI`. 
My advise is to take the files as an assumption. I am totally aware of the fact that all path specifications in my helperfiles have to be changed for non `RPI` installations!

I would be glad if someone could do the testing on other platforms. And ideally add the changes/enhancements to the helperfiles.

**Pull request closed without merging**
